using System.Diagnostics.Metrics;
using System.Text.RegularExpressions;
using FluentAssertions;
using FuelFlow.SharedKernel.Observability;

namespace FuelFlow.UnitTests.Observability;

/// <summary>
/// Guards the contract between the instruments declared in <see cref="FuelFlowMetrics"/> and the
/// metric names referenced by the Prometheus alert rules.
/// <para>
/// This exists because of a real outage-class bug: the OpenTelemetry Prometheus exporter injects
/// the instrument's <em>unit</em> into the exported name (so <c>fuelflow.jobs.failed</c> with unit
/// <c>jobs</c> is exported as <c>fuelflow_jobs_failed_jobs_total</c>, not
/// <c>fuelflow_jobs_failed_total</c>). Alert rules written against the intuitive name match nothing
/// and stay silent forever, which looks identical to "everything is healthy". Renaming an
/// instrument or merely changing its unit is enough to silently break an alert, and nothing else in
/// the build would notice.
/// </para>
/// </summary>
public class MetricNameContractTests
{
    /// <summary>
    /// Units are emitted in their expanded form (UCUM abbreviations are spelled out). Only the
    /// units actually used by <see cref="FuelFlowMetrics"/> need to be listed.
    /// </summary>
    private static readonly Dictionary<string, string> UnitSuffixes = new()
    {
        ["ms"] = "milliseconds",
        ["s"] = "seconds"
    };

    /// <summary>
    /// Reproduces the exporter's naming: dots become underscores, the unit is appended, and
    /// counters (monotonic sums) additionally get <c>_total</c>. Verified against a live scrape of
    /// both the API and the JobsWorker.
    /// </summary>
    private static string ToPrometheusName(string instrumentName, string? unit, bool isCounter)
    {
        var name = instrumentName.Replace('.', '_');

        if (!string.IsNullOrEmpty(unit))
        {
            var suffix = UnitSuffixes.TryGetValue(unit, out var mapped) ? mapped : unit;
            name = $"{name}_{suffix}";
        }

        return isCounter ? $"{name}_total" : name;
    }

    /// <summary>
    /// Collects every instrument published by <see cref="FuelFlowMetrics"/>, including the
    /// observable gauges, which are only created when their registration method is called.
    /// </summary>
    private static IReadOnlyList<string> GetExportedMetricNames()
    {
        var names = new List<string>();

        using var listener = new MeterListener();
        listener.InstrumentPublished = (instrument, l) =>
        {
            if (instrument.Meter.Name != ObservabilityConstants.MeterName) return;

            var isCounter = instrument.GetType().GetGenericTypeDefinition() == typeof(Counter<>);
            names.Add(ToPrometheusName(instrument.Name, instrument.Unit, isCounter));
            l.EnableMeasurementEvents(instrument);
        };
        listener.Start();

        using var metrics = new FuelFlowMetrics();
        metrics.RegisterVoucherPoolGauge(() => []);
        metrics.RegisterOrderStatusGauge(() => []);

        return names;
    }

    [Fact]
    public void EveryFuelFlowMetricReferencedByAlertRules_ExistsAsAnInstrument()
    {
        var rulesPath = Path.Combine(RepositoryRoot(), "backend", "observability", "prometheus", "rules", "fuelflow-alerts.yml");
        File.Exists(rulesPath).Should().BeTrue($"alert rules were expected at {rulesPath}");

        var exported = GetExportedMetricNames();

        // Bare metric selectors only: skip histogram-derived suffixes, which are generated by the
        // exporter rather than declared as instruments.
        var referenced = Regex.Matches(File.ReadAllText(rulesPath), @"\bfuelflow_[a-z0-9_]+\b")
            .Select(m => m.Value)
            .Select(n => Regex.Replace(n, "_(bucket|sum|count)$", string.Empty))
            .Distinct()
            .ToList();

        referenced.Should().NotBeEmpty("the alert rules are expected to reference FuelFlow metrics");

        foreach (var name in referenced)
        {
            exported.Should().Contain(name,
                $"alert rules query '{name}', but no instrument in FuelFlowMetrics exports that name. " +
                $"Remember the exporter injects the unit into the name. Exported: {string.Join(", ", exported.Order())}");
        }
    }

    [Theory]
    // The three names the business alert rules depend on. Pinned explicitly so that renaming an
    // instrument or changing its unit fails here with an obvious message.
    [InlineData("fuelflow_jobs_failed_jobs_total")]
    [InlineData("fuelflow_fulfillment_failed_orders_total")]
    [InlineData("fuelflow_vouchers_pool_available_vouchers")]
    public void AlertTargetedMetrics_KeepTheirExportedNames(string expectedName)
    {
        GetExportedMetricNames().Should().Contain(expectedName);
    }

    private static string RepositoryRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !Directory.Exists(Path.Combine(dir.FullName, ".git")))
        {
            dir = dir.Parent;
        }

        dir.Should().NotBeNull("the tests must run from inside the repository");
        return dir!.FullName;
    }
}
