namespace FuelFlow.Features.Auth.SharedModels;

/// <summary>
/// Represents a registered device for hardware-bound authentication.
/// Each device has a unique ID and public key for signature verification.
/// </summary>
public sealed class Device
{
    public Guid Id { get; set; }

    /// <summary>
    /// The user this device belongs to (references User.Id).
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Unique device identifier generated by the mobile app (UUID).
    /// </summary>
    public string DeviceId { get; set; } = string.Empty;

    /// <summary>
    /// Public key for verifying request signatures (PEM format).
    /// The corresponding private key never leaves the device.
    /// </summary>
    public string PublicKey { get; set; } = string.Empty;

    /// <summary>
    /// Device model (e.g., "iPhone 14 Pro", "Samsung Galaxy S23").
    /// </summary>
    public string? DeviceModel { get; set; }

    /// <summary>
    /// Operating system version (e.g., "iOS 17.2", "Android 14").
    /// </summary>
    public string? OsVersion { get; set; }

    /// <summary>
    /// App version at registration time (e.g., "1.0.0").
    /// </summary>
    public string? AppVersion { get; set; }

    /// <summary>
    /// Device status: ACTIVE, REVOKED.
    /// Revoked devices cannot authenticate even with valid signatures.
    /// </summary>
    public DeviceStatus Status { get; set; } = DeviceStatus.Active;

    /// <summary>
    /// When the device was first registered.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Last time this device made a successful authenticated request.
    /// </summary>
    public DateTime LastSeenAt { get; set; }

    // Navigation properties
    public User? User { get; set; }
}

/// <summary>
/// Device status enum.
/// </summary>
public enum DeviceStatus
{
    Active,
    Revoked
}
