using System.Runtime.CompilerServices;
using FluentAssertions;

namespace FuelFlow.UnitTests.Architecture;

/// <summary>
/// Architecture guard for the NoTracking mutation trap.
///
/// The API's ApplicationDbContext runs with a global QueryTrackingBehavior.NoTracking
/// default (DatabaseSetup). A handler that loads an entity WITHOUT .AsTracking(), mutates
/// a property on it, and calls SaveChanges persists NOTHING — the entity is untracked, so
/// the change tracker has no entry. It fails silently: no error, the handler reports success.
/// This has bitten real code five times (PR #566: SetUserActive/Role/Banned; PR #570:
/// DeleteMyOrder, ProductOwnerBootstrap — the last a silent ProductOwner grant).
///
/// This test catches the shape at CI time instead of in production: every source file that
/// calls SaveChanges must also carry an explicit persistence-intent marker — either
/// .AsTracking() on the load, or a .Add()/.Update()/.Remove() (which change entity state
/// regardless of the tracking default), or a bulk/raw operation that bypasses the tracker.
///
/// KNOWN BLIND SPOT (documented, accepted): a handler that BOTH .Add()s one entity AND
/// mutates a *different* loaded-but-untracked entity passes this check — the .Add() marker
/// satisfies the scan while the untracked mutation still silently fails. Catching that needs
/// data-flow analysis (Roslyn), which is disproportionate: the audit for PR #570 checked all
/// 59 SaveChanges sites and found zero such masked cases. If a sixth instance ever surfaces
/// with that shape, revisit with a semantic analyzer. See memory: notracking-mutation-trap.
/// </summary>
public sealed class NoTrackingMutationGuardTests
{
    // A file that persists is safe if it shows intent to change tracked state. AsTracking
    // re-enables tracking on the load; Add/Update/Remove attach state explicitly; the
    // Execute*/raw-SQL forms bypass the change tracker entirely and always hit the database.
    private static readonly string[] PersistenceMarkers =
    [
        ".AsTracking(",
        ".Add(", ".AddAsync(", ".AddRange(", ".AddRangeAsync(",
        ".Update(", ".UpdateRange(",
        ".Remove(", ".RemoveRange(",
        "ExecuteUpdate", "ExecuteDelete", "ExecuteSql",
    ];

    [Fact]
    public void EverySaveChangesSite_DeclaresPersistenceIntent()
    {
        var apiRoot = LocateApiProjectRoot();

        var offenders = Directory
            .EnumerateFiles(apiRoot, "*.cs", SearchOption.AllDirectories)
            .Where(IsInScope)
            .Select(path => (path, text: File.ReadAllText(path)))
            // Only files that actually persist are in scope.
            .Where(f => f.text.Contains("SaveChanges"))
            // Interfaces/abstract signatures merely DECLARE SaveChangesAsync; they never
            // mutate. Require a concrete type before demanding a persistence marker.
            .Where(f => DeclaresConcreteType(f.text))
            .Where(f => !PersistenceMarkers.Any(f.text.Contains))
            .Select(f => Path.GetRelativePath(apiRoot, f.path).Replace('\\', '/'))
            .OrderBy(p => p)
            .ToList();

        offenders.Should().BeEmpty(
            "every handler/service that calls SaveChanges must show persistence intent " +
            "(.AsTracking() on the load, or .Add()/.Update()/.Remove(), or a bulk/raw op) — " +
            "under the global NoTracking default, mutating an untracked entity makes SaveChanges " +
            "a silent no-op. If a flagged file is a legitimate exception, add it to the documented " +
            "allowlist in this test with the reason. See memory: notracking-mutation-trap.");
    }

    // Files generated by EF migrations and the DbContext plumbing itself are infrastructure,
    // not handlers, and legitimately call SaveChanges without a per-call mutation marker.
    private static bool IsInScope(string path)
    {
        var normalized = path.Replace('\\', '/');
        if (normalized.Contains("/Migrations/")) return false;
        if (normalized.Contains("/bin/") || normalized.Contains("/obj/")) return false;
        if (normalized.EndsWith("/ApplicationDbContext.cs")) return false;
        return true;
    }

    private static bool DeclaresConcreteType(string text) =>
        text.Contains("class ") || text.Contains("record ") || text.Contains("struct ");

    /// <summary>
    /// Resolves backend/src/FuelFlow.API from this test file's compile-time location, with a
    /// fallback that walks up from the test assembly's directory. Build and test run on the
    /// same checkout here, so the source tree is always present.
    /// </summary>
    private static string LocateApiProjectRoot([CallerFilePath] string thisFile = "")
    {
        // thisFile = .../backend/tests/FuelFlow.UnitTests/Architecture/<this>.cs
        // Up 3: FuelFlow.UnitTests -> tests -> backend
        var backend = Directory.GetParent(thisFile)!.Parent!.Parent!.Parent!.FullName;
        var candidate = Path.Combine(backend, "src", "FuelFlow.API");
        if (Directory.Exists(candidate)) return candidate;

        // Fallback: climb from the running assembly until a backend/src/FuelFlow.API appears.
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            var probe = Path.Combine(dir.FullName, "src", "FuelFlow.API");
            if (Directory.Exists(probe)) return probe;
            probe = Path.Combine(dir.FullName, "backend", "src", "FuelFlow.API");
            if (Directory.Exists(probe)) return probe;
            dir = dir.Parent;
        }

        throw new DirectoryNotFoundException(
            "Could not locate backend/src/FuelFlow.API from either the test file path or the assembly directory.");
    }
}
