// <auto-generated />
using System;
using FuelFlow.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FuelFlow.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FuelFlow.Features.Auth.SharedModels.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("app_version");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device_id");

                    b.Property<string>("DeviceModel")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("device_model");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("OsVersion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("os_version");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("public_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("FuelFlow.Features.Auth.SharedModels.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("FuelFlow.Features.Auth.SharedModels.VerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("verification_codes", (string)null);
                });

            modelBuilder.Entity("FuelFlow.Features.Contracts.SharedModels.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("LegalEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_entity_id");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("station_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("LegalEntityId");

                    b.HasIndex("StationId");

                    b.HasIndex("UserId");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("FuelFlow.Features.Contracts.SharedModels.LegalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DirectorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("director_name");

                    b.Property<string>("Edrpou")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("edrpou");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("vat_number");

                    b.HasKey("Id");

                    b.HasIndex("Edrpou")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("legal_entities", (string)null);
                });

            modelBuilder.Entity("FuelFlow.Features.Contracts.SharedModels.UserContract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<string>("SignatureData")
                        .HasColumnType("text")
                        .HasColumnName("signature_data");

                    b.Property<DateTime>("SignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("UserId");

                    b.ToTable("user_contracts", (string)null);
                });

            modelBuilder.Entity("FuelFlow.Features.Notifications.SharedModels.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("message");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("FuelFlow.Features.Orders.SharedModels.Fulfillment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FulfilledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fulfilled_at_utc");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("VoucherId")
                        .HasColumnType("uuid")
                        .HasColumnName("voucher_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("VoucherId");

                    b.ToTable("fulfillments", (string)null);
                });

            modelBuilder.Entity("FuelFlow.Features.Orders.SharedModels.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FuelTypeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fuel_type_id");

                    b.Property<DateTime?>("FulfilledAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fulfilled_at_utc");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<int>("Liters")
                        .HasColumnType("integer")
                        .HasColumnName("liters");

                    b.Property<string>("MonobankInvoiceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("monobank_invoice_id");

                    b.Property<string>("MonobankPaymentUrl")
                        .HasColumnType("text");

                    b.Property<string>("MonobankStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("monobank_status");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("product_type");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("idempotency_key IS NOT NULL");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("FuelFlow.Features.Orders.SharedModels.OutboxEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<bool>("Processed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("processed");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Processed");

                    b.ToTable("outbox_events", (string)null);
                });

            modelBuilder.Entity("FuelFlow.Features.Purchases.SharedModels.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("purchases", (string)null);
                });

            modelBuilder.Entity("FuelFlow.Features.Vouchers.FuelVoucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedToUserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date")
                        .HasColumnName("expiration_date");

                    b.Property<string>("FuelSubtype")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("fuel_subtype");

                    b.Property<string>("FuelTypeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("fuel_type_id");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<Guid?>("ImportJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_job_id");

                    b.Property<decimal>("Liters")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("liters");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<Guid?>("QrParametersId")
                        .HasColumnType("uuid")
                        .HasColumnName("qr_parameters_id");

                    b.Property<string>("QrPayload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qr_payload");

                    b.Property<string>("RedemptionRules")
                        .HasColumnType("text")
                        .HasColumnName("redemption_rules");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<double?>("VerificationMismatchPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("verification_mismatch_percent");

                    b.Property<int?>("VerificationMismatchedModules")
                        .HasColumnType("integer")
                        .HasColumnName("verification_mismatched_modules");

                    b.Property<int?>("VerificationTotalModules")
                        .HasColumnType("integer")
                        .HasColumnName("verification_total_modules");

                    b.Property<string>("VoucherNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("voucher_number");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ExpirationDate");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("Provider");

                    b.HasIndex("QrParametersId");

                    b.HasIndex("QrPayload")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("VoucherNumber")
                        .IsUnique();

                    b.HasIndex("Provider", "FuelTypeId", "Liters", "Status");

                    b.ToTable("fuel_vouchers", (string)null);
                });

            modelBuilder.Entity("FuelFlow.Features.Vouchers.QrParameters", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EccLevel")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("ecc_level");

                    b.Property<string>("EncodingMode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("encoding_mode");

                    b.Property<int?>("MaskPattern")
                        .HasColumnType("integer")
                        .HasColumnName("mask_pattern");

                    b.Property<int?>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("EccLevel", "Version", "MaskPattern", "EncodingMode")
                        .IsUnique();

                    b.ToTable("qr_parameters", (string)null);
                });

            modelBuilder.Entity("FuelFlow.Features.Vouchers.SharedModels.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to_user_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_id");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fuel_type");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("vouchers", (string)null);
                });

            modelBuilder.Entity("FuelFlow.Features.Vouchers.VoucherImport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("integer")
                        .HasColumnName("duplicate_count");

                    b.Property<int>("FailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_count");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<int>("ImportedCount")
                        .HasColumnType("integer")
                        .HasColumnName("imported_count");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("VerificationFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("verification_failed_count");

                    b.Property<int>("VerifiedWithWarningsCount")
                        .HasColumnType("integer")
                        .HasColumnName("verified_with_warnings_count");

                    b.HasKey("Id");

                    b.ToTable("voucher_imports", (string)null);
                });

            modelBuilder.Entity("FuelFlow.Features.Vouchers.VoucherImportError", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid>("ImportId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_id");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("page_number");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("VoucherNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("voucher_number");

                    b.HasKey("Id");

                    b.HasIndex("ImportId");

                    b.ToTable("voucher_import_errors", (string)null);
                });

            modelBuilder.Entity("FuelFlow.SharedKernel.Domain.FuelPackage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("FuelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fuel_name");

                    b.Property<string>("FuelTypeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fuel_type_id");

                    b.Property<int>("Liters")
                        .HasColumnType("integer")
                        .HasColumnName("liters");

                    b.Property<int>("OriginalPrice")
                        .HasColumnType("integer")
                        .HasColumnName("original_price");

                    b.Property<int>("Price")
                        .HasColumnType("integer")
                        .HasColumnName("price");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("station_id");

                    b.HasKey("Id");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("StationId");

                    b.ToTable("fuel_packages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "okko-dp-10",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "ДП ЄВРО",
                            FuelTypeId = "okko-dp",
                            Liters = 10,
                            OriginalPrice = 550,
                            Price = 520,
                            StationId = "okko"
                        },
                        new
                        {
                            Id = "okko-dp-20",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "ДП ЄВРО",
                            FuelTypeId = "okko-dp",
                            Liters = 20,
                            OriginalPrice = 1100,
                            Price = 1040,
                            StationId = "okko"
                        },
                        new
                        {
                            Id = "okko-dp-50",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "ДП ЄВРО",
                            FuelTypeId = "okko-dp",
                            Liters = 50,
                            OriginalPrice = 2750,
                            Price = 2600,
                            StationId = "okko"
                        },
                        new
                        {
                            Id = "okko-95-10",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "A-95",
                            FuelTypeId = "okko-95",
                            Liters = 10,
                            OriginalPrice = 550,
                            Price = 520,
                            StationId = "okko"
                        },
                        new
                        {
                            Id = "okko-95-20",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "A-95",
                            FuelTypeId = "okko-95",
                            Liters = 20,
                            OriginalPrice = 1100,
                            Price = 1040,
                            StationId = "okko"
                        },
                        new
                        {
                            Id = "okko-95-50",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "A-95",
                            FuelTypeId = "okko-95",
                            Liters = 50,
                            OriginalPrice = 2750,
                            Price = 2600,
                            StationId = "okko"
                        },
                        new
                        {
                            Id = "okko-p95-10",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "Pulls 95",
                            FuelTypeId = "okko-p95",
                            Liters = 10,
                            OriginalPrice = 620,
                            Price = 580,
                            StationId = "okko"
                        },
                        new
                        {
                            Id = "okko-p95-20",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "Pulls 95",
                            FuelTypeId = "okko-p95",
                            Liters = 20,
                            OriginalPrice = 1240,
                            Price = 1160,
                            StationId = "okko"
                        },
                        new
                        {
                            Id = "okko-p95-50",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "Pulls 95",
                            FuelTypeId = "okko-p95",
                            Liters = 50,
                            OriginalPrice = 3100,
                            Price = 2900,
                            StationId = "okko"
                        },
                        new
                        {
                            Id = "okko-pulls-dp-10",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "ДП PULLS",
                            FuelTypeId = "okko-pulls-dp",
                            Liters = 10,
                            OriginalPrice = 580,
                            Price = 550,
                            StationId = "okko"
                        },
                        new
                        {
                            Id = "okko-pulls-dp-20",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "ДП PULLS",
                            FuelTypeId = "okko-pulls-dp",
                            Liters = 20,
                            OriginalPrice = 1160,
                            Price = 1100,
                            StationId = "okko"
                        },
                        new
                        {
                            Id = "okko-pulls-dp-50",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "ДП PULLS",
                            FuelTypeId = "okko-pulls-dp",
                            Liters = 50,
                            OriginalPrice = 2900,
                            Price = 2750,
                            StationId = "okko"
                        },
                        new
                        {
                            Id = "okko-gas-10",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "ГАЗ",
                            FuelTypeId = "okko-gas",
                            Liters = 10,
                            OriginalPrice = 300,
                            Price = 280,
                            StationId = "okko"
                        },
                        new
                        {
                            Id = "okko-gas-20",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "ГАЗ",
                            FuelTypeId = "okko-gas",
                            Liters = 20,
                            OriginalPrice = 600,
                            Price = 560,
                            StationId = "okko"
                        },
                        new
                        {
                            Id = "okko-gas-50",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "ГАЗ",
                            FuelTypeId = "okko-gas",
                            Liters = 50,
                            OriginalPrice = 1500,
                            Price = 1400,
                            StationId = "okko"
                        },
                        new
                        {
                            Id = "wog-dp-10",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "ДП Mustang",
                            FuelTypeId = "wog-dp",
                            Liters = 10,
                            OriginalPrice = 560,
                            Price = 530,
                            StationId = "wog"
                        },
                        new
                        {
                            Id = "wog-dp-20",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "ДП Mustang",
                            FuelTypeId = "wog-dp",
                            Liters = 20,
                            OriginalPrice = 1120,
                            Price = 1060,
                            StationId = "wog"
                        },
                        new
                        {
                            Id = "wog-dp-50",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "ДП Mustang",
                            FuelTypeId = "wog-dp",
                            Liters = 50,
                            OriginalPrice = 2800,
                            Price = 2650,
                            StationId = "wog"
                        },
                        new
                        {
                            Id = "wog-95-10",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "A-95 Mustang",
                            FuelTypeId = "wog-95",
                            Liters = 10,
                            OriginalPrice = 560,
                            Price = 530,
                            StationId = "wog"
                        },
                        new
                        {
                            Id = "wog-95-20",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "A-95 Mustang",
                            FuelTypeId = "wog-95",
                            Liters = 20,
                            OriginalPrice = 1120,
                            Price = 1060,
                            StationId = "wog"
                        },
                        new
                        {
                            Id = "wog-95-50",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "A-95 Mustang",
                            FuelTypeId = "wog-95",
                            Liters = 50,
                            OriginalPrice = 2800,
                            Price = 2650,
                            StationId = "wog"
                        },
                        new
                        {
                            Id = "wog-95-euro-10",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "A 95 EURO",
                            FuelTypeId = "wog-95-euro",
                            Liters = 10,
                            OriginalPrice = 550,
                            Price = 520,
                            StationId = "wog"
                        },
                        new
                        {
                            Id = "wog-95-euro-20",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "A 95 EURO",
                            FuelTypeId = "wog-95-euro",
                            Liters = 20,
                            OriginalPrice = 1100,
                            Price = 1040,
                            StationId = "wog"
                        },
                        new
                        {
                            Id = "wog-95-euro-50",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "A 95 EURO",
                            FuelTypeId = "wog-95-euro",
                            Liters = 50,
                            OriginalPrice = 2750,
                            Price = 2600,
                            StationId = "wog"
                        },
                        new
                        {
                            Id = "wog-100-10",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "Mustang 100",
                            FuelTypeId = "wog-100",
                            Liters = 10,
                            OriginalPrice = 650,
                            Price = 600,
                            StationId = "wog"
                        },
                        new
                        {
                            Id = "wog-100-20",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "Mustang 100",
                            FuelTypeId = "wog-100",
                            Liters = 20,
                            OriginalPrice = 1300,
                            Price = 1200,
                            StationId = "wog"
                        },
                        new
                        {
                            Id = "wog-100-50",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "Mustang 100",
                            FuelTypeId = "wog-100",
                            Liters = 50,
                            OriginalPrice = 3250,
                            Price = 3000,
                            StationId = "wog"
                        },
                        new
                        {
                            Id = "wog-gas-10",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "ГАЗ",
                            FuelTypeId = "wog-gas",
                            Liters = 10,
                            OriginalPrice = 300,
                            Price = 280,
                            StationId = "wog"
                        },
                        new
                        {
                            Id = "wog-gas-20",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "ГАЗ",
                            FuelTypeId = "wog-gas",
                            Liters = 20,
                            OriginalPrice = 600,
                            Price = 560,
                            StationId = "wog"
                        },
                        new
                        {
                            Id = "wog-gas-50",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "ГАЗ",
                            FuelTypeId = "wog-gas",
                            Liters = 50,
                            OriginalPrice = 1500,
                            Price = 1400,
                            StationId = "wog"
                        },
                        new
                        {
                            Id = "okko-dp-2",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "ДП ЄВРО",
                            FuelTypeId = "okko-dp",
                            Liters = 2,
                            OriginalPrice = 110,
                            Price = 104,
                            StationId = "okko"
                        },
                        new
                        {
                            Id = "okko-dp-3",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FuelName = "ДП ЄВРО",
                            FuelTypeId = "okko-dp",
                            Liters = 3,
                            OriginalPrice = 165,
                            Price = 156,
                            StationId = "okko"
                        });
                });

            modelBuilder.Entity("FuelFlow.SharedKernel.Domain.FuelTypeEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("BasePrice")
                        .HasColumnType("integer")
                        .HasColumnName("base_price");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DiscountPrice")
                        .HasColumnType("integer")
                        .HasColumnName("discount_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("station_id");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("fuel_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "okko-dp",
                            BasePrice = 55,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPrice = 52,
                            Name = "ДП ЄВРО",
                            StationId = "okko"
                        },
                        new
                        {
                            Id = "okko-95",
                            BasePrice = 55,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPrice = 52,
                            Name = "A-95",
                            StationId = "okko"
                        },
                        new
                        {
                            Id = "okko-p95",
                            BasePrice = 62,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPrice = 58,
                            Name = "Pulls 95",
                            StationId = "okko"
                        },
                        new
                        {
                            Id = "okko-pulls-dp",
                            BasePrice = 58,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPrice = 55,
                            Name = "ДП PULLS",
                            StationId = "okko"
                        },
                        new
                        {
                            Id = "okko-gas",
                            BasePrice = 30,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPrice = 28,
                            Name = "ГАЗ",
                            StationId = "okko"
                        },
                        new
                        {
                            Id = "wog-dp",
                            BasePrice = 56,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPrice = 53,
                            Name = "ДП Mustang",
                            StationId = "wog"
                        },
                        new
                        {
                            Id = "wog-95",
                            BasePrice = 56,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPrice = 53,
                            Name = "A-95 Mustang",
                            StationId = "wog"
                        },
                        new
                        {
                            Id = "wog-95-euro",
                            BasePrice = 55,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPrice = 52,
                            Name = "A 95 EURO",
                            StationId = "wog"
                        },
                        new
                        {
                            Id = "wog-100",
                            BasePrice = 65,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPrice = 60,
                            Name = "Mustang 100",
                            StationId = "wog"
                        },
                        new
                        {
                            Id = "wog-gas",
                            BasePrice = 30,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPrice = 28,
                            Name = "ГАЗ",
                            StationId = "wog"
                        });
                });

            modelBuilder.Entity("FuelFlow.SharedKernel.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("FuelFlow.SharedKernel.Domain.Station", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("#00ff80")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Lat")
                        .HasColumnType("text")
                        .HasColumnName("lat");

                    b.Property<string>("Lng")
                        .HasColumnType("text")
                        .HasColumnName("lng");

                    b.Property<string>("LogoText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("logo_text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("StationType")
                        .HasColumnType("text")
                        .HasColumnName("station_type");

                    b.HasKey("Id");

                    b.ToTable("stations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "okko",
                            Color = "#22c55e",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Lat = "50.4851",
                            Lng = "30.4734",
                            LogoText = "OKKO",
                            Name = "OKKO"
                        },
                        new
                        {
                            Id = "wog",
                            Color = "#10b981",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Lat = "50.4501",
                            Lng = "30.5234",
                            LogoText = "WOG",
                            Name = "WOG"
                        },
                        new
                        {
                            Id = "upg",
                            Color = "#06b6d4",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Lat = "50.4001",
                            Lng = "30.6134",
                            LogoText = "UPG",
                            Name = "UPG"
                        },
                        new
                        {
                            Id = "klo",
                            Color = "#eab308",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Lat = "50.4101",
                            Lng = "30.4034",
                            LogoText = "KLO",
                            Name = "KLO"
                        });
                });

            modelBuilder.Entity("FuelFlow.SharedKernel.Domain.StationNode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Lat")
                        .HasColumnType("text")
                        .HasColumnName("lat");

                    b.Property<string>("Lng")
                        .HasColumnType("text")
                        .HasColumnName("lng");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("station_id");

                    b.Property<string>("StationType")
                        .HasColumnType("text")
                        .HasColumnName("station_type");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("station_nodes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "okko-kyiv-main",
                            Address = "42 Чоколівський бульвар",
                            City = "Київ",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Lat = "50.4310",
                            Lng = "30.4515",
                            Name = "OKKO Київ",
                            StationId = "okko",
                            StationType = "Тип АЗС ОККО-міська"
                        },
                        new
                        {
                            Id = "wog-kyiv-main",
                            Address = "15-Б проспект Соборності",
                            City = "Київ",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Lat = "50.4482",
                            Lng = "30.6170",
                            Name = "WOG Київ",
                            StationId = "wog",
                            StationType = "Тип АЗС WOG-міська"
                        },
                        new
                        {
                            Id = "upg-kyiv-main",
                            Address = "Проспект Перемоги, 98",
                            City = "Київ",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Lat = "50.4566",
                            Lng = "30.3950",
                            Name = "UPG Київ",
                            StationId = "upg",
                            StationType = "Тип АЗС UPG-міська"
                        },
                        new
                        {
                            Id = "klo-kyiv-main",
                            Address = "Броварський проспект, 11",
                            City = "Київ",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Lat = "50.4578",
                            Lng = "30.5986",
                            Name = "KLO Київ",
                            StationId = "klo",
                            StationType = "Тип АЗС KLO-міська"
                        });
                });

            modelBuilder.Entity("FuelFlow.SharedKernel.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("Birthdate")
                        .HasColumnType("date")
                        .HasColumnName("birthdate");

                    b.Property<int>("BonusBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("bonus_balance");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("profile_image_url");

                    b.Property<string>("ReferralCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("referral_code");

                    b.Property<string>("ReferredBy")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("referred_by");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("ReferralCode")
                        .IsUnique()
                        .HasFilter("referral_code IS NOT NULL");

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FuelFlow.Features.Auth.SharedModels.Device", b =>
                {
                    b.HasOne("FuelFlow.SharedKernel.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuelFlow.Features.Auth.SharedModels.RefreshToken", b =>
                {
                    b.HasOne("FuelFlow.SharedKernel.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuelFlow.Features.Contracts.SharedModels.Contract", b =>
                {
                    b.HasOne("FuelFlow.Features.Contracts.SharedModels.LegalEntity", "Entity")
                        .WithMany()
                        .HasForeignKey("LegalEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelFlow.SharedKernel.Domain.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelFlow.SharedKernel.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");

                    b.Navigation("Station");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuelFlow.Features.Contracts.SharedModels.LegalEntity", b =>
                {
                    b.HasOne("FuelFlow.SharedKernel.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuelFlow.Features.Contracts.SharedModels.UserContract", b =>
                {
                    b.HasOne("FuelFlow.Features.Contracts.SharedModels.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelFlow.SharedKernel.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuelFlow.Features.Notifications.SharedModels.Notification", b =>
                {
                    b.HasOne("FuelFlow.SharedKernel.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuelFlow.Features.Orders.SharedModels.Fulfillment", b =>
                {
                    b.HasOne("FuelFlow.Features.Orders.SharedModels.Order", null)
                        .WithMany("Fulfillments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FuelFlow.Features.Purchases.SharedModels.Purchase", b =>
                {
                    b.HasOne("FuelFlow.SharedKernel.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuelFlow.Features.Vouchers.FuelVoucher", b =>
                {
                    b.HasOne("FuelFlow.SharedKernel.Domain.FuelTypeEntity", "FuelType")
                        .WithMany()
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FuelFlow.Features.Vouchers.QrParameters", "QrParameters")
                        .WithMany()
                        .HasForeignKey("QrParametersId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FuelType");

                    b.Navigation("QrParameters");
                });

            modelBuilder.Entity("FuelFlow.Features.Vouchers.VoucherImportError", b =>
                {
                    b.HasOne("FuelFlow.Features.Vouchers.VoucherImport", null)
                        .WithMany()
                        .HasForeignKey("ImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FuelFlow.SharedKernel.Domain.StationNode", b =>
                {
                    b.HasOne("FuelFlow.SharedKernel.Domain.Station", null)
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FuelFlow.SharedKernel.Domain.User", b =>
                {
                    b.HasOne("FuelFlow.SharedKernel.Domain.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FuelFlow.Features.Orders.SharedModels.Order", b =>
                {
                    b.Navigation("Fulfillments");
                });
#pragma warning restore 612, 618
        }
    }
}
